name: skybase
description: Code base for flutter using provider.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0-alpha.1+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Architecture
  provider: ^6.1.2
  go_router: ^14.0.1
  dio: ^5.4.3+1
  get_it: ^7.7.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3
  easy_localization: ^3.0.6
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.3

  # File Manager
  path_provider: ^2.1.3
  image_picker: ^1.1.0
  file_picker: ^8.0.3
  flutter_image_compress: ^2.2.0
  path: ^1.9.0

  # Widget
  modal_bottom_sheet: ^3.0.0
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  # Others
  collection: ^1.18.0
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  url_launcher: ^6.2.6
  permission_handler: ^11.3.1
  intl: ^0.19.0
  open_filex: ^4.4.0
  device_preview: ^1.1.0
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_native_splash: ^2.4.0
#  change_app_package_name: ^1.1.0
#  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - lib/core/localization/languages/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300

#
# Usage :
# flutter pub run flutter_launcher_icons
#
#flutter_icons:
#  image_path: "assets/images/logo/app_logo.png"
#  min_sdk_android: 21
#  ios: true
#  android: true
#  remove_alpha_ios: true (Optional)
#  background_color_ios: "#ffffff" (Optional)